# controller_manager provides the necessary infrastructure to manage multiple controllers
# efficiently and robustly using ROS 2 Control.
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    # Declare the controllers
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

# Parameters for the mecanum drive controller
mecanum_drive_controller:
  ros__parameters:
    # Command joint names
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_right_wheel_command_joint_name: "back_right_wheel_joint"
    rear_left_wheel_command_joint_name: "back_left_wheel_joint"

    # State joint names
    front_left_wheel_state_joint_name: "front_left_wheel_joint"
    front_right_wheel_state_joint_name: "front_right_wheel_joint"
    rear_right_wheel_state_joint_name: "back_right_wheel_joint"
    rear_left_wheel_state_joint_name: "back_left_wheel_joint"

    kinematics:
      wheels_radius: 0.0325
      sum_of_robot_center_projection_on_X_Y_axis: 0.1645

    # TF configuration
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    enable_odom_tf: true

    # Odometry parameters
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # Command handling
    reference_timeout: 0.5
    use_stamped_vel: true
