version: '3.8'

services:
  navigation_humble:
    build:
      context: ..
      dockerfile: docker/robot_humble/Dockerfile
    network_mode: host
    restart: always
    volumes:
      - ../src:/ros_ws/src
    #entrypoint: /home/ros/entrypoint.sh
    environment:
      - ROS_DOMAIN_ID=28
    command: >
      bash /ros_ws/src/scripts/run_navigation.sh
      

  localization_jazzy:
    build:
      context: ..
      dockerfile: docker/robot_jazzy/Dockerfile
    network_mode: host
    restart: always
    volumes:
      - ../src:/ros_ws/src
      #- ./docker/scripts/:/ros_ws/
    #entrypoint: /home/ros/entrypoint.sh
    environment:
      - ROS_DOMAIN_ID=28
    command: >
     bash /ros_ws/src/scripts/run_localisation.sh
      
