version: '3.8'

services:
  navigation_humble:
    build:
      context: ..
      dockerfile: docker/robot_humble/Dockerfile
    network_mode: host
    restart: always
    environment:
      - ROS_DOMAIN_ID=28
    command: >
      bash -c "source /ros_ws/install/setup.bash &&
               ros2 launch yahboom_rosmaster_bringup rosmaster_x3_navigation.launch.py"

  localization_jazzy:
    build:
      context: ..
      dockerfile: docker/robot_jazzy/Dockerfile
    network_mode: host
    restart: always
    environment:
      - ROS_DOMAIN_ID=28
    command: >
      bash -c "source /ros_ws/install/setup.bash &&
               ros2 launch yahboom_rosmaster_localization rosmaster_localization.launch.py"
