version: '3.8'

services:
  gazebo:
    image: gzserver:lts
    network_mode: host
    volumes:
      - ../worlds:/worlds

  robot_nodes_humble:
    build:
      context: ..
      dockerfile: docker/robot_humble/Dockerfile
    network_mode: host
    volumes:
      - ../src:/ros_ws/src
      - ../docker/scripts/entrypoint.sh:/ros_ws/entrypoint.sh
    entrypoint: /ros_ws/entrypoint.sh
    environment:
      - ROS_DOMAIN_ID=28
    command: >
      ros2 launch yahboom_rosmaster_bringup yahboom_rosmaster_simulation.launch.py use_sim_time:=true

  robot_nodes_jazzy:
    build:
      context: ..
      dockerfile: docker/robot_jazzy/Dockerfile
    network_mode: host
    volumes:
      - ../src:/ros_ws/src
      - ../docker/scripts/entrypoint.sh:/ros_ws/entrypoint.sh
    entrypoint: /ros_ws/entrypoint.sh
    environment:
      - ROS_DOMAIN_ID=28
    command: >
      ros2 launch yahboom_rosmaster_bringup yahboom_rosmaster_simulation.launch.py use_sim_time:=true

  station_tools:
    build:
      context: ..
      dockerfile: docker/station/Dockerfile
    network_mode: host
    volumes:
      - ../src:/ros_ws/src
      - ../docker/scripts/entrypoint.sh:/ros_ws/entrypoint.sh
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: /ros_ws/entrypoint.sh
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=28
