version: '3.8'
services:
  # Outil de visualisation
  rviz_station:
    build:
      context: ../
      dockerfile: docker/station/Dockerfile
    command: rviz2 -d /ros_ws/src/bringup/config/default.rviz
    network_mode: host # Nécessaire pour découvrir les topics du robot sur le LAN
    privileged: true # Souvent requis pour l'accès au matériel graphique
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=42 # Doit correspondre à celui du robot
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # Partage du socket X11 pour la GUI
      # - ../docker/common/cyclone_dds.xml:/path/to/cyclone_dds.xml