version: '3.8'

services:
  station_tools:
    build:
      context: ..
      dockerfile: docker/station/Dockerfile
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=28
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: >
      bash -c "source /ros_ws/install/setup.bash &&
               rviz2"
